
//질문게시판 관련
export const REQUEST_QUESTION_BOARD_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_LIST_TO_SPRING'
export const REQUEST_QUESTION_BOARD_TO_SPRING = 'REQUEST_QUESTION_BOARD_TO_SPRING'

//게시물 검색 관련
export const REQUEST_SEARCH_BOARD_TO_SPRING = 'REQUEST_SEARCH_BOARD_TO_SPRING'

//댓글 관련
export const REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING'
// export const REQUEST_QUESTION_BOARD_VIEW_CNT_INCREASE_TO_SPRING ='REQUEST_QUESTION_BOARD_VIEW_CNT_INCREASE_TO_SPRING'
