
// 상품 관련
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'
export const REQUEST_ALL_PRODUCT_TO_SPRING = 'REQUEST_ALL_PRODUCT_TO_SPRING'


//질문게시판 관련
export const REQUEST_QUESTION_BOARD_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_LIST_TO_SPRING'
export const REQUEST_QUESTION_BOARD_TO_SPRING = 'REQUEST_QUESTION_BOARD_TO_SPRING'


//댓글 관련
export const REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING'

//주문 관련
export const REQUEST_ORDER_INFORMATIONS_TO_SPRING = 'REQUEST_ORDER_INFORMATIONS_TO_SPRING'

//공지사항 게시판관련
export const REQUEST_NOTICE_BOARD_LIST_TO_SPRING = 'REQUEST_NOTICE_BOARD_LIST_TO_SPRING'
export const REQUEST_NOTICE_BOARD_TO_SPRING = 'REQUEST_NOTICE_BOARD_TO_SPRING'

