
// 상품 관련
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'
export const REQUEST_ALL_PRODUCT_TO_SPRING = 'REQUEST_ALL_PRODUCT_TO_SPRING'

// 보드 관련
export const REQUEST_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_FREE_BOARD_LIST_TO_SPRING'
export const REQUEST_FREE_BOARD_TO_SPRING = 'REQUEST_FREE_BOARD_TO_SPRING'


//질문게시판 관련
export const REQUEST_QUESTION_BOARD_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_LIST_TO_SPRING'
export const REQUEST_QUESTION_BOARD_TO_SPRING = 'REQUEST_QUESTION_BOARD_TO_SPRING'

//리뷰게시판 관련
export const REQUEST_REVIEW_BOARD_LIST_TO_SPRING = 'REQUEST_REVIEW_BOARD_LIST_TO_SPRING'
export const REQUEST_REVIEW_BOARD_TO_SPRING = 'REQUEST_REVIEW_BOARD_TO_SPRING'
export const REQUEST_REVIEW_BOARD_IMAGE_LIST_TO_SPRING = 'REQUEST_REVIEW_BOARD_IMAGE_LIST_TO_SPRING'

//댓글 관련
export const REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING'

//주문 관련
export const REQUEST_ORDER_INFORMATIONS_TO_SPRING = 'REQUEST_ORDER_INFORMATIONS_TO_SPRING'
//게시물 검색 관련
export const REQUEST_SEARCH_BOARD_TO_SPRING = 'REQUEST_SEARCH_BOARD_TO_SPRING'

//공지사항 게시판관련
export const REQUEST_NOTICE_BOARD_LIST_TO_SPRING = 'REQUEST_NOTICE_BOARD_LIST_TO_SPRING'
export const REQUEST_NOTICE_BOARD_TO_SPRING = 'REQUEST_NOTICE_BOARD_TO_SPRING'

//나의 게시판 관련
export const REQUEST_MY_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_MY_FREE_BOARD_LIST_TO_SPRING'

// 마이페이지 내 정보 관련
export const REQUEST_MY_INFO_TO_SPRING = 'REQUEST_MY_INFO_TO_SPRING'

//나의 질문게시판 관련
export const REQUEST_MY_QUESTION_BOARD_LIST_TO_SPRING = 'REQUEST_MY_QUESTION_BOARD_LIST_TO_SPRING'