//이벤트관련
export const REQUEST_EVENT_LIST_TO_SPRING = 'REQUEST_EVENT_LIST_TO_SPRING'
export const REQUEST_EVENT_DETAIL_TO_SPRING = 'REQUEST_EVENT_DETAIL_TO_SPRING'
export const REQUEST_CAFE_BY_EVENT_SPRING = 'REQUEST_CAFE_BY_EVENT_SPRING'

