//주문 관련
export const REQUEST_ORDER_INFORMATIONS_TO_SPRING = 'REQUEST_ORDER_INFORMATIONS_TO_SPRING'
export const UPDATE_IS_ORDER_PACKING = 'UPDATE_IS_ORDER_PACKING'
export const REQUEST_HOLD_POINT_TO_SPRING = 'REQUEST_HOLD_POINT_TO_SPRING'
export const REQUEST_CAFE_ORDER_LIST_TO_SPRING = 'REQUEST_CAFE_ORDER_LIST_TO_SPRING'