//예약관련
export const REQUEST_CAFE_SEAT_TO_SPRING = 'REQUEST_CAFE_SEAT_TO_SPRING'
//카페소개보드관련
export const REQUEST_CAFE_LIST_TO_SPRING = 'REQUEST_CAFE_LIST_TO_SPRING'
export const REQUEST_CAFE_NUM_TO_SPRING= 'REQUEST_CAFE_NUM_TO_SPRING'
export const REQUEST_CAFE_DETAIL_TO_SPRING= 'REQUEST_CAFE_DETAIL_TO_SPRING'

// 상품 관련
export const REQUEST_PRODUCT_LIST_TO_SPRING = 'REQUEST_PRODUCT_LIST_TO_SPRING'
export const REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING = 'REQUEST_PRODUCT_IMAGE_LIST_TO_SPRING'
export const REQUEST_ALL_PRODUCT_TO_SPRING = 'REQUEST_ALL_PRODUCT_TO_SPRING'

// 보드 관련
export const REQUEST_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_FREE_BOARD_LIST_TO_SPRING'
export const REQUEST_FREE_BOARD_TO_SPRING = 'REQUEST_FREE_BOARD_TO_SPRING'


//질문게시판 관련
export const REQUEST_QUESTION_BOARD_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_LIST_TO_SPRING'
export const REQUEST_QUESTION_BOARD_TO_SPRING = 'REQUEST_QUESTION_BOARD_TO_SPRING'

//리뷰게시판 관련
export const REQUEST_REVIEW_BOARD_LIST_TO_SPRING = 'REQUEST_REVIEW_BOARD_LIST_TO_SPRING'
export const REQUEST_REVIEW_BOARD_TO_SPRING = 'REQUEST_REVIEW_BOARD_TO_SPRING'
export const REQUEST_REVIEW_BOARD_IMAGE_LIST_TO_SPRING = 'REQUEST_REVIEW_BOARD_IMAGE_LIST_TO_SPRING'

//댓글 관련
export const REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING = 'REQUEST_QUESTION_BOARD_COMMENT_LIST_TO_SPRING'