export const REQUEST_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_FREE_BOARD_LIST_TO_SPRING'
export const REQUEST_FREE_BOARD_TO_SPRING = 'REQUEST_FREE_BOARD_TO_SPRING'

//댓글 관련
export const REQUEST_FREE_BOARD_COMMENT_LIST_TO_SPRING = 'REQUEST_FREE_BOARD_COMMENT_LIST_TO_SPRING'

//게시물 검색 관련
export const  REQUEST_SEARCH_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_SEARCH_FREE_BOARD_LIST_TO_SPRING'

export const REQUEST_FREE_BOARD_IMAGE_LIST_TO_SPRING = 'REQUEST_FREE_BOARD_IMAGE_LIST_TO_SPRING'
export const REQUEST_BEST_FREE_BOARD_LIST_TO_SPRING = 'REQUEST_BEST_FREE_BOARD_LIST_TO_SPRING'