//카페소개보드관련
export const REQUEST_CAFE_LIST_TO_SPRING = 'REQUEST_CAFE_LIST_TO_SPRING'
export const REQUEST_CAFE_NUM_TO_SPRING= 'REQUEST_CAFE_NUM_TO_SPRING'
export const REQUEST_CAFE_DETAIL_TO_SPRING= 'REQUEST_CAFE_DETAIL_TO_SPRING'
export const REQUEST_CAFE_TOP3_TO_SPRING= 'REQUEST_CAFE_TOP3_TO_SPRING'


